name: gha_zadanie2:Zadanie2

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-push-images-with-cache:
    name: Build and push Docker image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHC_TOKEN}}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/x86_64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner}}/zadanie2:v1.0.0


      # - name: Docker Scout
      #   id: docker-scout
      #   if: ${{ github.event_name == 'push' }}
      #   uses: docker/scout-action@dd36f5b0295baffa006aa6623371f226cc03e506
      #   with:
      #     command: compare
      #     image: ghcr.io/${{ github.repository_owner}}/zadanie2
      #     to: ghcr.io/${{ github.repository_owner}}/zadanie2
      #     ignore-unchanged: true
      #     only-severities: critical,high
      #     token: ${{ secrets.DOCKERHUB_TOKEN }}
